"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ChevronLeft, ChevronRight, MapPin, Waves } from "lucide-react";

export type ObservationArea = { name: string; count: number; detections: number; latitude: number; longitude: number; primaryClass: string | null };
type Sea = "동해" | "서해" | "남해" | "제주";
type Beach = { id: string; name: string; sea: Sea; latitude: number; longitude: number; municipalityCode: string };
type BeachStat = Beach & { count: number; detections: number; primaryClass: string | null; locations: ObservationArea[]; classCounts: Map<string, number>; isOther?: boolean };

const BEACHES: Beach[] = [
  { id:"sokcho",name:"속초해수욕장",sea:"동해",latitude:38.189,longitude:128.601,municipalityCode:"32060" }, { id:"gyeongpo",name:"경포해수욕장",sea:"동해",latitude:37.805,longitude:128.907,municipalityCode:"32030" }, { id:"mangsang",name:"망상해수욕장",sea:"동해",latitude:37.593,longitude:129.090,municipalityCode:"32040" }, { id:"yeongildae",name:"영일대해수욕장",sea:"동해",latitude:36.061,longitude:129.378,municipalityCode:"37012" },
  { id:"eulwangri",name:"을왕리해수욕장",sea:"서해",latitude:37.447,longitude:126.372,municipalityCode:"23010" }, { id:"mallipo",name:"만리포해수욕장",sea:"서해",latitude:36.789,longitude:126.144,municipalityCode:"34380" }, { id:"daecheon",name:"대천해수욕장",sea:"서해",latitude:36.304,longitude:126.511,municipalityCode:"34030" }, { id:"byeonsan",name:"변산해수욕장",sea:"서해",latitude:35.682,longitude:126.529,municipalityCode:"35380" },
  { id:"haeundae",name:"해운대해수욕장",sea:"남해",latitude:35.159,longitude:129.160,municipalityCode:"21090" }, { id:"gwangalli",name:"광안리해수욕장",sea:"남해",latitude:35.153,longitude:129.118,municipalityCode:"21140" }, { id:"sangju",name:"상주은모래비치",sea:"남해",latitude:34.720,longitude:127.987,municipalityCode:"38350" }, { id:"manseongri",name:"만성리해수욕장",sea:"남해",latitude:34.777,longitude:127.744,municipalityCode:"36020" },
  { id:"hyeopjae",name:"협재해수욕장",sea:"제주",latitude:33.394,longitude:126.239,municipalityCode:"39010" }, { id:"hamdeok",name:"함덕해수욕장",sea:"제주",latitude:33.543,longitude:126.669,municipalityCode:"39010" }, { id:"jungmun",name:"중문색달해수욕장",sea:"제주",latitude:33.245,longitude:126.411,municipalityCode:"39020" }, { id:"iho",name:"이호테우해수욕장",sea:"제주",latitude:33.497,longitude:126.453,municipalityCode:"39010" },
  { id:"naksan",name:"낙산해수욕장",sea:"동해",latitude:38.116,longitude:128.631,municipalityCode:"32400" }, { id:"samcheok",name:"삼척해수욕장",sea:"동해",latitude:37.469,longitude:129.165,municipalityCode:"32070" }, { id:"jangsa",name:"장사해수욕장",sea:"동해",latitude:36.283,longitude:129.376,municipalityCode:"37350" },
  { id:"kkotji",name:"꽃지해수욕장",sea:"서해",latitude:36.500,longitude:126.335,municipalityCode:"34380" }, { id:"muchangpo",name:"무창포해수욕장",sea:"서해",latitude:36.244,longitude:126.536,municipalityCode:"34030" }, { id:"seonyudo",name:"선유도해수욕장",sea:"서해",latitude:35.813,longitude:126.412,municipalityCode:"35020" },
  { id:"songjeong",name:"송정해수욕장",sea:"남해",latitude:35.178,longitude:129.199,municipalityCode:"21090" }, { id:"gujora",name:"구조라해수욕장",sea:"남해",latitude:34.809,longitude:128.690,municipalityCode:"38090" }, { id:"songho",name:"송호해수욕장",sea:"남해",latitude:34.315,longitude:126.519,municipalityCode:"38310" },
  { id:"woljeongri",name:"월정리해수욕장",sea:"제주",latitude:33.556,longitude:126.795,municipalityCode:"39010" }, { id:"pyoseon",name:"표선해수욕장",sea:"제주",latitude:33.327,longitude:126.837,municipalityCode:"39020" }, { id:"gwakji",name:"곽지해수욕장",sea:"제주",latitude:33.450,longitude:126.305,municipalityCode:"39010" },
];
const DEMO_AREAS: ObservationArea[] = [
  {name:"강원특별자치도 속초시 조양동 속초해수욕장",count:18,detections:326,latitude:38.188,longitude:128.602,primaryClass:"PET_Bottle"},{name:"강원특별자치도 강릉시 안현동 경포해수욕장",count:11,detections:184,latitude:37.806,longitude:128.908,primaryClass:"Plastic ETC"},{name:"강원특별자치도 동해시 망상동 망상해수욕장",count:6,detections:79,latitude:37.594,longitude:129.089,primaryClass:"Rope"},{name:"경상북도 포항시 북구 영일대해수욕장",count:3,detections:41,latitude:36.061,longitude:129.379,primaryClass:"Styrofoam Piece"},{name:"강원특별자치도 고성군 죽왕면 해안",count:8,detections:116,latitude:38.330,longitude:128.532,primaryClass:"Net"},
  {name:"인천광역시 중구 을왕동 을왕리해수욕장",count:14,detections:251,latitude:37.446,longitude:126.373,primaryClass:"PET_Bottle"},{name:"충청남도 태안군 소원면 만리포해수욕장",count:9,detections:137,latitude:36.790,longitude:126.145,primaryClass:"Plastic Buoy"},{name:"충청남도 보령시 신흑동 대천해수욕장",count:22,detections:418,latitude:36.305,longitude:126.512,primaryClass:"Styrofoam Box"},{name:"전북특별자치도 부안군 변산면 변산해수욕장",count:5,detections:64,latitude:35.682,longitude:126.530,primaryClass:"Glass"},{name:"충청남도 서산시 대산읍 연안",count:12,detections:205,latitude:36.950,longitude:126.350,primaryClass:"Rope"},
  {name:"부산광역시 해운대구 해운대해수욕장",count:25,detections:463,latitude:35.159,longitude:129.160,primaryClass:"PET_Bottle"},{name:"부산광역시 수영구 광안리해수욕장",count:17,detections:287,latitude:35.153,longitude:129.119,primaryClass:"Plastic ETC"},{name:"경상남도 남해군 상주면 상주은모래비치",count:7,detections:93,latitude:34.720,longitude:127.987,primaryClass:"Styrofoam Buoy"},{name:"전라남도 여수시 만흥동 만성리해수욕장",count:4,detections:52,latitude:34.778,longitude:127.745,primaryClass:"Metal"},{name:"경상남도 통영시 산양읍 연안",count:10,detections:148,latitude:34.780,longitude:128.395,primaryClass:"Net"},
  {name:"제주특별자치도 제주시 한림읍 협재해수욕장",count:16,detections:279,latitude:33.394,longitude:126.240,primaryClass:"PET_Bottle"},{name:"제주특별자치도 제주시 조천읍 함덕해수욕장",count:13,detections:221,latitude:33.543,longitude:126.670,primaryClass:"Plastic ETC"},{name:"제주특별자치도 서귀포시 중문색달해수욕장",count:8,detections:105,latitude:33.245,longitude:126.412,primaryClass:"Styrofoam Piece"},{name:"제주특별자치도 제주시 이호일동 이호테우해수욕장",count:2,detections:19,latitude:33.498,longitude:126.454,primaryClass:"Glass"},{name:"제주특별자치도 서귀포시 성산읍 연안",count:11,detections:176,latitude:33.450,longitude:126.935,primaryClass:"Plastic Buoy(China)"},
  {name:"강원특별자치도 양양군 강현면 낙산해수욕장",count:15,detections:238,latitude:38.116,longitude:128.631,primaryClass:"PET_Bottle"},{name:"강원특별자치도 삼척시 갈천동 삼척해수욕장",count:7,detections:92,latitude:37.469,longitude:129.165,primaryClass:"Metal"},{name:"경상북도 영덕군 남정면 장사해수욕장",count:4,detections:57,latitude:36.283,longitude:129.376,primaryClass:"Rope"},
  {name:"충청남도 태안군 안면읍 꽃지해수욕장",count:19,detections:342,latitude:36.500,longitude:126.335,primaryClass:"Styrofoam Box"},{name:"충청남도 보령시 웅천읍 무창포해수욕장",count:8,detections:121,latitude:36.244,longitude:126.536,primaryClass:"Plastic Buoy"},{name:"전북특별자치도 군산시 옥도면 선유도해수욕장",count:3,detections:38,latitude:35.813,longitude:126.412,primaryClass:"Glass"},
  {name:"부산광역시 해운대구 송정동 송정해수욕장",count:21,detections:376,latitude:35.178,longitude:129.199,primaryClass:"PET_Bottle"},{name:"경상남도 거제시 일운면 구조라해수욕장",count:9,detections:144,latitude:34.809,longitude:128.690,primaryClass:"Net"},{name:"전라남도 해남군 송지면 송호해수욕장",count:5,detections:68,latitude:34.315,longitude:126.519,primaryClass:"Styrofoam Buoy"},
  {name:"제주특별자치도 제주시 구좌읍 월정리해수욕장",count:20,detections:319,latitude:33.556,longitude:126.795,primaryClass:"PET_Bottle"},{name:"제주특별자치도 서귀포시 표선면 표선해수욕장",count:10,detections:158,latitude:33.327,longitude:126.837,primaryClass:"Plastic ETC"},{name:"제주특별자치도 제주시 애월읍 곽지해수욕장",count:6,detections:74,latitude:33.450,longitude:126.305,primaryClass:"Styrofoam Piece"},
];
export const OBSERVATION_DUMMY_CLASS_SUMMARY = Array.from(DEMO_AREAS.reduce((map,area)=>{if(area.primaryClass)map.set(area.primaryClass,(map.get(area.primaryClass)??0)+area.detections);return map;},new Map<string,number>()),([name,count])=>({name,count})).sort((a,b)=>b.count-a.count);
const SEAS: Sea[] = ["동해","서해","남해","제주"];
const SEA_VIEWS: Record<Sea, { viewBox: string; className: string; caption: string }> = {
  동해: { viewBox:"330 25 255 430", className:"east", caption:"강원·경북 동해안 확대" },
  서해: { viewBox:"65 105 270 390", className:"west", caption:"인천·충남·전북 서해안 확대" },
  남해: { viewBox:"250 420 340 220", className:"south", caption:"전남·경남·부산 남해안 확대" },
  제주: { viewBox:"130 600 310 155", className:"jeju", caption:"제주도 주요 해안 확대" },
};

function distanceKm(aLat:number,aLon:number,bLat:number,bLon:number) { const r=6371; const dLat=(bLat-aLat)*Math.PI/180; const dLon=(bLon-aLon)*Math.PI/180; const q=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLon/2)**2; return 2*r*Math.asin(Math.sqrt(q)); }
function fallbackSea(lat:number,lon:number):Sea { if(lat<34.15)return "제주"; if(lon>=128.05)return lat<35.35?"남해":"동해"; if(lat<35.25)return "남해"; return "서해"; }
function provinceFromAddress(address?:string){if(!address)return null;const aliases:[[string,string]]|Array<[string,string]>=[["강원","강원도"],["경상북","경상북도"],["경상남","경상남도"],["전라북","전라북도"],["전북","전라북도"],["전라남","전라남도"],["충청남","충청남도"],["인천","인천광역시"],["부산","부산광역시"],["울산","울산광역시"],["제주","제주특별자치도"]];return aliases.find(([keyword])=>address.includes(keyword))?.[1]??null;}
const PROVINCE_SEA: Record<string,Sea>={강원도:"동해",경상북도:"동해",인천광역시:"서해",경기도:"서해",충청남도:"서해",전라북도:"서해",전라남도:"남해",광주광역시:"남해",경상남도:"남해",부산광역시:"남해",울산광역시:"남해",제주특별자치도:"제주"};
const SEA_COLORS:Record<Sea,string>={동해:"#327f7c",서해:"#3d9992",남해:"#55b7ad",제주:"#48a9a1"};
const OTHER_MUNICIPALITY:Record<Sea,string>={동해:"32400",서해:"34050",남해:"38050",제주:"39020"};
const MUNICIPAL_VIEWS:Record<Sea,string>={동해:"127.55 -38.72 2.35 3.18",서해:"125.55 -38.05 2.12 3.22",남해:"126.45 -35.58 3.25 1.72",제주:"125.95 -33.62 1.22 .56"};
type GeoFeature={properties:{code:string;name:string};geometry:{type:"Polygon"|"MultiPolygon";coordinates:number[][][]|number[][][][]}};
function ringPath(ring:number[][]){return ring.map(([x,y],index)=>`${index?"L":"M"}${x} ${-y}`).join(" ")+" Z";}
function featurePath(feature:GeoFeature){const coordinates=feature.geometry.coordinates;return feature.geometry.type==="Polygon"?(coordinates as number[][][]).map(ringPath).join(" "):(coordinates as number[][][][]).flatMap(polygon=>polygon.map(ringPath)).join(" ");}

export function AdminObservationMap({ areas }: { areas: ObservationArea[] }) {
  const baseMapRef=useRef<HTMLDivElement>(null); const [sea,setSea]=useState<Sea|null>(null); const [selected,setSelected]=useState<string|null>(null); const [placePage,setPlacePage]=useState(1);
  const stats=useMemo(()=>{
    const map=new Map<string,BeachStat>(); for(const beach of BEACHES)map.set(beach.id,{...beach,count:0,detections:0,primaryClass:null,locations:[],classCounts:new Map()});
    for(const area of [...DEMO_AREAS,...areas]){const nearest=BEACHES.map(beach=>({beach,distance:distanceKm(area.latitude,area.longitude,beach.latitude,beach.longitude)})).sort((a,b)=>a.distance-b.distance)[0]; const target=nearest&&nearest.distance<=5?nearest.beach:null; const coast=fallbackSea(area.latitude,area.longitude);const key=target?.id??`other-${coast}`; const value:BeachStat=map.get(key)??{id:key,name:`기타 ${coast} 연안`,sea:coast,latitude:area.latitude,longitude:area.longitude,municipalityCode:OTHER_MUNICIPALITY[coast],count:0,detections:0,primaryClass:null,locations:[],classCounts:new Map<string,number>(),isOther:true}; value.count+=area.count;value.detections+=area.detections;value.locations.push(area);if(area.primaryClass)value.classCounts.set(area.primaryClass,(value.classCounts.get(area.primaryClass)??0)+area.detections);value.primaryClass=Array.from(value.classCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]??null;map.set(key,value);}
    return Array.from(map.values());
  },[areas]);
  const visible=sea?stats.filter(item=>item.sea===sea).sort((a,b)=>b.count-a.count||b.detections-a.detections):[]; const placePageSize=5; const placePageCount=Math.max(1,Math.ceil(visible.length/placePageSize)); const safePlacePage=Math.min(placePage,placePageCount); const pagedVisible=visible.slice((safePlacePage-1)*placePageSize,safePlacePage*placePageSize); const max=Math.max(...visible.map(item=>item.count),1); const selectedStat=stats.find(item=>item.id===selected); const activeView=sea?MUNICIPAL_VIEWS[sea]:"0 0 800 759";
  useEffect(()=>{setPlacePage(1)},[sea]);
  const selectedProvince=provinceFromAddress(selectedStat?.locations[0]?.name);
  useEffect(()=>{let live=true;
    if(sea){
      fetch("/korea-municipalities.json").then(r=>r.json()).then((collection:{features:GeoFeature[]})=>{
        if(!live||!baseMapRef.current)return;
        const ns="http://www.w3.org/2000/svg",svg=document.createElementNS(ns,"svg");svg.setAttribute("viewBox",activeView);svg.setAttribute("preserveAspectRatio","xMidYMid meet");svg.classList.add("municipality-svg");
        const byCode=new Map<string,BeachStat[]>();visible.forEach(item=>byCode.set(item.municipalityCode,[...(byCode.get(item.municipalityCode)??[]),item]));
        for(const feature of collection.features){const path=document.createElementNS(ns,"path"),items=byCode.get(feature.properties.code)??[],total=items.reduce((sum,item)=>sum+item.count,0),active=items.some(item=>item.id===selected);path.setAttribute("d",featurePath(feature));path.setAttribute("data-code",feature.properties.code);path.setAttribute("fill",active?"#e87855":total?`rgba(91, ${Math.max(145,198-Math.min(total,30))}, ${Math.max(139,190-Math.min(total,30))}, ${.48+Math.min(total/65,.34)})`:"#123f43");path.setAttribute("stroke",active?"#ffd3c5":"#81b9b4");path.setAttribute("stroke-width",active?".012":".006");path.setAttribute("vector-effect","non-scaling-stroke");path.classList.add(items.length?"observed-municipality":"quiet-municipality");if(items.length){const title=document.createElementNS(ns,"title");title.textContent=`${feature.properties.name} · ${items.map(item=>item.name).join(", ")} · 관측 ${total}건`;path.append(title);path.addEventListener("click",event=>{event.stopPropagation();const next=[...items].sort((a,b)=>b.count-a.count)[0];setSelected(current=>current===next.id?null:next.id)});}svg.append(path);}
        baseMapRef.current.replaceChildren(svg);
      });return()=>{live=false};
    }
    fetch("/korea-provinces.svg").then(r=>r.text()).then(source=>{
    if(!live||!baseMapRef.current)return;
    const parsed=new DOMParser().parseFromString(source,"image/svg+xml"),svg=parsed.documentElement;
    svg.removeAttribute("width");svg.removeAttribute("height");svg.setAttribute("viewBox",activeView);svg.setAttribute("preserveAspectRatio","xMidYMid meet");
    for(const path of Array.from(svg.querySelectorAll<SVGPathElement>("path"))){const region=PROVINCE_SEA[path.id];const fill=!sea?(region?SEA_COLORS[region]:"#123f43"):region===sea?"#245f60":"#123f43";path.setAttribute("fill",fill);path.setAttribute("stroke","#82b9b4");path.setAttribute("stroke-width",sea?"1.05":"1.2");if(!sea&&region){path.classList.add("coast-province");path.setAttribute("data-sea",region);}}
    baseMapRef.current.replaceChildren(document.importNode(svg,true));const rendered=baseMapRef.current.querySelector("svg");if(!rendered)return;
    for(const path of Array.from(rendered.querySelectorAll<SVGPathElement>(".coast-province"))){const region=PROVINCE_SEA[path.id];if(region){const group=()=>Array.from(rendered.querySelectorAll<SVGPathElement>(`.coast-province[data-sea="${region}"]`));path.addEventListener("pointerenter",()=>group().forEach(item=>item.classList.add("sea-group-hover")));path.addEventListener("pointerleave",()=>group().forEach(item=>item.classList.remove("sea-group-hover")));path.addEventListener("click",()=>{setSea(region);setSelected(null)});}}
  });return()=>{live=false};},[sea,activeView,selected,areas]);
  const seaTotals=SEAS.map(item=>({sea:item,count:stats.filter(stat=>stat.sea===item).reduce((sum,stat)=>sum+stat.count,0),detections:stats.filter(stat=>stat.sea===item).reduce((sum,stat)=>sum+stat.detections,0)}));
  return <div className="beach-report">
    <nav className="beach-sea-tabs" aria-label="해역 선택">{SEAS.map(item=><button type="button" className={sea===item?"active":""} key={item} onClick={()=>{setSea(current=>current===item?null:item);setSelected(null)}}>{item}<small>{stats.filter(stat=>stat.sea===item).reduce((sum,stat)=>sum+stat.count,0)}건</small></button>)}</nav>
    {!sea?<div className="coast-overview-body"><section className="coast-overview-list"><header><span>KOREA COAST</span><h4>전국 연안 관측 구역</h4><p>권역을 선택하면 대표 장소가 확대됩니다.</p></header><div>{seaTotals.map((item,index)=><button type="button" key={item.sea} onClick={()=>setSea(item.sea)}><i style={{background:SEA_COLORS[item.sea]}}/><span><small>0{index+1}</small><strong>{item.sea} 연안</strong><em>{item.detections.toLocaleString()}개 부유물 탐지</em></span><b>{item.count}<small>관측</small></b></button>)}</div></section><section className="coast-overview-map"><div ref={baseMapRef} className="beach-map-base"/><div className="coast-overview-caption"><MapPin size={15}/><span>권역을 지도에서 선택할 수 있습니다</span></div><div className="coast-region-labels">{seaTotals.map(item=><button key={item.sea} className={item.sea} onClick={()=>setSea(item.sea)}><strong>{item.sea}</strong><small>{item.count}건</small></button>)}</div></section></div>:<div className="beach-report-body">
      <section className="beach-rank-chart"><header><span>{sea.toUpperCase()} COAST</span><h4>{sea} 장소별 관측 섹션</h4><p>해수욕장과 기타 연안을 분리해 관리합니다.</p></header><div className="beach-place-page" key={`${sea}-${safePlacePage}`}>{pagedVisible.map((item,index)=><button type="button" key={item.id} className={`${selected===item.id?"active ":""}${item.isOther?"other-section":"beach-section"}`} onClick={()=>setSelected(current=>current===item.id?null:item.id)}><i>{String((safePlacePage-1)*placePageSize+index+1).padStart(2,"0")}</i><span><strong>{item.name}</strong><small>{item.primaryClass?`주요 탐지 · ${item.primaryClass}`:"탐지 기록 없음"}</small><em><b style={{width:`${item.count?Math.max(8,item.count/max*100):0}%`}}/></em></span><small><b>{item.isOther?"기타 연안":"대표 해수욕장"}</b>{item.count}건</small></button>)}</div>{placePageCount>1&&<nav className="beach-place-pagination" aria-label={`${sea} 장소 목록 페이지`}><button type="button" aria-label="이전 페이지" disabled={safePlacePage===1} onClick={()=>setPlacePage(page=>Math.max(1,page-1))}><ChevronLeft size={14}/></button><span><b>{safePlacePage}</b> / {placePageCount}</span><button type="button" aria-label="다음 페이지" disabled={safePlacePage===placePageCount} onClick={()=>setPlacePage(page=>Math.min(placePageCount,page+1))}><ChevronRight size={14}/></button></nav>}</section>
      <section className={`beach-marker-map sea-${SEA_VIEWS[sea].className}${selectedStat?" place-zoomed":""}`} onClick={()=>setSelected(null)}><div ref={baseMapRef} className="beach-map-base administrative-map"/><div className="beach-map-title"><MapPin size={15}/><span>{selectedStat?`${selectedStat.name} 소속 행정구역`:SEA_VIEWS[sea].caption}</span></div><div className="beach-map-kind"><span><i className="district-line"/>행정구역 경계</span><span><i className="selected-area"/>선택 장소 소속 지역</span></div>{selectedStat&&<aside className="beach-map-reading"><Waves size={17}/><div><span>{selectedStat.isOther?"OTHER COAST":"BEACH AREA"}</span><strong>{selectedStat.name}</strong><p>고유 관측 {selectedStat.count}건 · 탐지 {selectedStat.detections.toLocaleString()}건</p><small>{selectedProvince??"행정구역 확인 중"} · {selectedStat.primaryClass?`주요 탐지 ${selectedStat.primaryClass}`:"탐지 기록 없음"}</small></div></aside>}</section>
    </div>}
  </div>;
}
