"use client";

import { FormEvent, useState } from "react";
import { LoaderCircle, MapPin, Navigation, Search, X } from "lucide-react";
import { api } from "@/lib/api";
import { LocationMap } from "./location-map";

export type RealtimeLocation = { latitude:number; longitude:number; location_name:string; location_description:string; coastal_eligible:boolean };

export function RealtimeLocationDialog({ initial, onClose, onConfirm }: { initial:RealtimeLocation|null; onClose:()=>void; onConfirm:(location:RealtimeLocation)=>void }) {
  const [latitude,setLatitude]=useState<number|null>(initial?.latitude??null),[longitude,setLongitude]=useState<number|null>(initial?.longitude??null);
  const [name,setName]=useState(initial?.location_name??""),[description,setDescription]=useState(initial?.location_description??""),[query,setQuery]=useState(initial?.location_name??"");
  const [results,setResults]=useState<Array<{name:string;latitude:number;longitude:number}>>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[eligible,setEligible]=useState(initial?.coastal_eligible??false);
  async function resolve(lat:number,lon:number){setLatitude(lat);setLongitude(lon);setResults([]);setBusy(true);setError("");try{const [address,coast]=await Promise.all([api<{name:string}>(`/locations/reverse?latitude=${lat}&longitude=${lon}`),api<{eligible:boolean;reason:string}>(`/locations/coastal-check?latitude=${lat}&longitude=${lon}`)]);setName(address.name);setQuery(address.name);setEligible(coast.eligible);if(!coast.eligible)setError("해안 관측 통계에는 해안선 인접 위치만 반영됩니다.");}catch(reason){setError(reason instanceof Error?reason.message:"위치 정보를 확인하지 못했습니다.");}finally{setBusy(false)}}
  async function search(event:FormEvent){event.preventDefault();if(query.trim().length<2)return;setBusy(true);setError("");try{setResults(await api(`/locations/search?q=${encodeURIComponent(query.trim())}`));}catch(reason){setError(reason instanceof Error?reason.message:"장소를 검색하지 못했습니다.");}finally{setBusy(false)}}
  return <div className="realtime-location-backdrop" role="presentation" onMouseDown={onClose}><section role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><header><div><small>LIVE OBSERVATION LOCATION</small><h2>실시간 촬영 위치</h2><p>관측 위치를 기록하면 탐지 결과를 지역 통계에 연결할 수 있습니다.</p></div><button onClick={onClose} aria-label="닫기"><X size={20}/></button></header><div className="realtime-location-content"><form onSubmit={search}><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="해수욕장, 항구 또는 주소 검색"/><button disabled={busy||query.trim().length<2}>{busy?<LoaderCircle className="spin" size={14}/>:"검색"}</button></form>{results.length>0&&<div className="realtime-location-results">{results.map((item,index)=><button key={`${item.latitude}-${index}`} onClick={()=>void resolve(item.latitude,item.longitude)}><MapPin size={14}/><span>{item.name}</span></button>)}</div>}<LocationMap latitude={latitude} longitude={longitude} onChange={(lat,lon)=>void resolve(lat,lon)}/><div className="realtime-location-selected"><MapPin size={17}/><div><small>선택한 위치</small><strong>{busy?"주소 확인 중...":name||"지도에서 위치를 선택해 주세요"}</strong>{latitude!=null&&longitude!=null&&<span>{latitude.toFixed(6)}, {longitude.toFixed(6)}</span>}</div>{latitude!=null&&<em className={eligible?"eligible":"excluded"}>{eligible?"해안 통계 반영":"통계 제외 위치"}</em>}</div><label><span>위치 추가 설명 <small>선택 사항</small></span><input maxLength={300} value={description} onChange={event=>setDescription(event.target.value)} placeholder="예: 방파제 입구에서 북쪽 방향으로 촬영"/></label>{error&&<p className="realtime-location-error">{error}</p>}</div><footer><button onClick={onClose}>취소</button><button className="primary" disabled={latitude==null||longitude==null||busy} onClick={()=>latitude!=null&&longitude!=null&&onConfirm({latitude,longitude,location_name:name,location_description:description,coastal_eligible:eligible})}><Navigation size={15}/>이 위치 사용</button></footer></section></div>;
}
